---
title: "Application reports"
author: "MyAI"
date: '`r format(Sys.Date(), "%b %d %Y", tz="Africa/Bissau")`'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, results = 'hide')
```

```{r}
library(dplyr)
library(RMySQL)
library(RJDBC)
library(knitr)
```

```{r}

#sQL for MySQL
query_mysql <- "SELECT CASE A.MODULE WHEN 'BUNDLES3G' then 'BUNDLES3G_EVD_123' ELSE A.MODULE END MODULE, B.TOTAL YESTERDAY, A.TOTAL TODAY, (A.TOTAL - B.TOTAL) DIFFERENCE, ROUND(A.TOTAL*100/(B.TOTAL), 1) PCT 
FROM (SELECT MODULE, COUNT(DISTINCT MSISDN) DIST ,COUNT(BUNDLE_PRICE) NBRE, SUM(BUNDLE_PRICE) TOTAL FROM COMMON.CDR
WHERE TRANSDATE = CURDATE() AND STATUS_REASON = 'BUNDLE_SUCCESS' AND LAST_UPDATE <= current_timestamp() GROUP BY MODULE) A 
LEFT JOIN (SELECT MODULE, COUNT(DISTINCT MSISDN)DIST,COUNT(BUNDLE_PRICE) NBRE, SUM(BUNDLE_PRICE) TOTAL FROM COMMON.CDR
WHERE TRANSDATE = date_sub(CURDATE(), INTERVAL 1 DAY) AND STATUS_REASON = 'BUNDLE_SUCCESS' AND LAST_UPDATE <= date_sub(current_timestamp(), interval 1 day)
GROUP BY MODULE) B USING (MODULE) ORDER BY PCT DESC"

#SQL for oracle
query_orcl <- "SELECT MODULE, B.TOTAL YESTERDAY, A.TOTAL TODAY, (A.TOTAL - B.TOTAL) DIFFERENCE, ROUND(A.TOTAL*100/(B.TOTAL), 1) PCT 
FROM (SELECT MODULE, COUNT(DISTINCT MSISDN) DIST ,COUNT(BUNDLE_PRICE) NBRE, SUM(BUNDLE_PRICE) TOTAL FROM CDR
WHERE TRANSDATE = trunc(sysdate) AND STATUS_REASON = 'BUNDLE_SUCCESS' AND LAST_UPDATE <= sysdate GROUP BY MODULE) A 
LEFT JOIN (SELECT MODULE, COUNT(DISTINCT MSISDN)DIST,COUNT(BUNDLE_PRICE) NBRE, SUM(BUNDLE_PRICE) TOTAL FROM CDR
WHERE TRANSDATE = trunc(sysdate-1) AND STATUS_REASON = 'BUNDLE_SUCCESS' AND LAST_UPDATE <= sysdate-1
GROUP BY MODULE) B USING (MODULE) ORDER BY PCT DESC"

#Connection to server 39
myDB39 <- dbConnect(MySQL(), user='everaldo', password='123456', dbname='COMMON', host='192.168.100.39')
rs39 <- dbSendQuery(myDB39, query_mysql)
data39 <- fetch(rs39, n=-1)


#Connection to server 15
myDB15 <- dbConnect(MySQL(), user='mtn', password='Mtn@123456', dbname='COMMON', host='192.168.100.15')
rs15 <- dbSendQuery(myDB15, query_mysql)
data15 <- fetch(rs15, n=-1)

#Connection to oracle server
drv <- JDBC("oracle.jdbc.OracleDriver", classPath = "lib/ojdbc6.jar")
orcl <- dbConnect(drv, "jdbc:oracle:thin:@//10.100.2.179:1521/vasdb", "vas", "vas")
dataOrcl <- dbGetQuery(orcl, query_orcl)

#bind dataframes
df <- rbind(data39, data15, dataOrcl)
rm(data39, data15, dataOrcl)

#Mutate final sdf and add datetime
df <- df %>% 
  #mutate("Current DateTime" = format(Sys.time(), "%X", tz="Africa/Bissau")) %>% 
  filter(MODULE != c('ECOMIB', 'SMSBUNDLE')) %>% 
  arrange(desc(TODAY))


#Clear resultset and close connections
dbClearResult(dbListResults(myDB15)[[1]])
dbClearResult(dbListResults(myDB39)[[1]])
dbDisconnect(myDB15)
dbDisconnect(myDB39)
dbDisconnect(orcl)
```

# Application Reports `r format(Sys.time(), "%a %b %d/%Y %X ", tz="Africa/Bissau")`

`r kable(df)`